# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peterborough.tech-community.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Free and open source blog for IT professionals in Peterborough. Populated by anybody thats has any kind of interest in IT.

  We are always looking for contributors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  peterborough.tech-community.co.uk

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "/blog/page:num/"

gems: ['jekyll-paginate']

